"""
Django settings for LITA project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

URL_BASIC = config('URL_BASIC')
URL_MAIN = config('URL_MAIN')

APPPLAT_KEY = config('APPPLAT_KEY')
APPPLAT_VALUE = config('APPPLAT_VALUE')
DNT_KEY = config('DNT_KEY')
DNT_VALUE = config('DNT_VALUE')
L_APP_ID_KEY = config('L_APP_ID_KEY')
L_APP_ID_VALUE = config('L_APP_ID_VALUE')
L_APP_PLATFORM_KEY = config('L_APP_PLATFORM_KEY')
L_APP_PLATFORM_VALUE = config('L_APP_PLATFORM_VALUE')
L_LOCALE_KEY = config('L_LOCALE_KEY')
L_LOCALE_VALUE = config('L_LOCALE_VALUE')
L_NONCE_KEY = config('L_NONCE_KEY')
L_SIGN_KEY = config('L_SIGN_KEY')
L_TIMESTAMP_KEY = config('L_TIMESTAMP_KEY')
L_TRACE_ID_KEY = config('L_TRACE_ID_KEY')
L_USER_LOCALE_KEY = config('L_USER_LOCALE_KEY')
L_USER_LOCALE_VALUE = config('L_USER_LOCALE_VALUE')
L_USER_TOKEN_KEY = config('L_USER_TOKEN_KEY')
L_USER_TOKEN_VALUE = config('L_USER_TOKEN_VALUE')
L_USER_TOKEN_VALUE_V2 = config('L_USER_TOKEN_VALUE_V2')
L_USER_TOKEN_VALUE_V3 = config('L_USER_TOKEN_VALUE_V3')
L_USER_TOKEN_VALUE_V4 = config('L_USER_TOKEN_VALUE_V4')
ORIGIN_KEY = config('ORIGIN_KEY')
ORIGIN_VALUE = config('ORIGIN_VALUE')
PROXYHEADER_KEY = config('PROXYHEADER_KEY')
PROXYHEADER_VALUE = config('PROXYHEADER_VALUE')
PROXYHEADER_VALUE_V2 = config('PROXYHEADER_VALUE_V2')
PROXYHEADER_VALUE_V3 = config('PROXYHEADER_VALUE_V3')
PROXYHEADER_VALUE_V4 = config('PROXYHEADER_VALUE_V4')
REFERER_KEY = config('REFERER_KEY')
REFERER_VALUE = config('REFERER_VALUE')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEVELOPMENT', default=False, cast=bool)

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '.vercel.app',
    '.ridwaanhall.me',
    '.ngoding.me',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'lita_fe.apps.LitaFeConfig',
    'lita_be.apps.LitaBeConfig',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LITA.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LITA.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
