name: Update Last Updated

on:
  push:
    branches:
      - main

jobs:
  update-last-updated:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update last_updated field
      run: |
        sed -i "s/\"last_updated\": \".*\"/\"last_updated\": \"$(date -u +'%Y-%m-%dT%H:%M:%SZ')\"/" LITA/views.py

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add LITA/views.py
        git commit -m "Update last_updated field"
        git push
